config/routes.rb
TestAppBeta::Application.routes.draw do
  
  root 'home#index'

  get "home/index"
  get "user/test_results"
  get "user/tests_given"
  get "author/question_by_author"
  get "teach/teach_tut"
  get "author/tutorials_by_author"
  get "author/exercise_by_author"
  resources :languages

  
  get "profile/viewtest"
  get "starttest/select_level"
  get "starttest/random_test"
  get "starttest/start"
  post "starttest/result"
  get "starttest/show_result"
  get "starttest/end_test"
  get "user/test_show_details"
  post "starttest/total_question"

  devise_for :users
  resources :options
 
  resources :questions
  resources :accept

  resources :addimages

  get "learn/index"
  get "learn/tutorial"
  get "learn/exercise"
  get "student/index"
  post "learn/myfunc"
  get "learn/output"
 resources :exercises

  resources :tutorials

  get '/tutorials/showbylanguage/:tutorial_id'=> "tutorials#showbylanguage"

 

 

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end

    if user.role == "Author"
        can :manage , :all
    else
        can :read ,:all
    end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/accept.rb
class Accept < ActiveRecord::Base
	belongs_to :test
end

app/models/addimage.rb
class Addimage < ActiveRecord::Base
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
	belongs_to :tutorial
	mount_uploader :video , VideoUploader
end

app/models/language.rb
class Language < ActiveRecord::Base
has_many :tutorials
end

app/models/option.rb
class Option < ActiveRecord::Base
	belongs_to :question
end

app/models/q_no.rb
class QNo < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
	
	has_one :option
	belongs_to :test
	accepts_nested_attributes_for :option
	has_many :settests
	has_many :tests, through: :settests
	belongs_to :language
end
  

app/models/settest.rb
class Settest < ActiveRecord::Base
	belongs_to :question
	belongs_to :test
	belongs_to :user

	accepts_nested_attributes_for :accept

end

app/models/test.rb
class Test < ActiveRecord::Base
	has_many :questions , through: :settests
	has_many :settests
	belongs_to :user
	has_many :accepts
end

app/models/tutorial.rb
class Tutorial < ActiveRecord::Base
  belongs_to :language
  has_many :exercises
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :tests
end

app/controllers/questions_controller.rb
  class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show

    @question = params[:id].to_i
    @question_full = Question.where(:id => @question)


  end

  # GET /questions/new
  def new
    @question = Question.new
        @question.build_option

  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render action: 'show', status: :created, location: @question }
      else
        format.html { render action: 'new' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:name,:user_id, :correct_choice ,:language_id, :difficulty_level,option_attributes: [:optionA,:optionB,:optionC,:optionD])
    end
end

app/helpers/addimages_helper.rb
module AddimagesHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/learn_helper.rb
module LearnHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/teach_helper.rb
module TeachHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/questions/_form.html.erb
<br>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
    <ul class="nav nav-tabs nav-stacked" style="position:fixed">
    <li><a href="#">Add a Question</a></li>
    <li><a href="#">Show Question Added by me</a></li>
</ul>
</div>
    <div class="span9">
    
      <div class="jumbotron">

    <p><h3 class="text-info">Add a Question</h3></p>
    <hr />
    
<%= simple_form_for @question do |f| %>
  <%= f.input :name, required: true, label: Question, :input_html => { class: 'span18',:rows => 4}  %>
  <%= f.association :language, :input_html => { class: 'span4',:rows => 8}  %>
  <%= f.input :user_id ,:as => "hidden",:input_html => {:value => current_user.id } %>
  <hr>
  
  <%= f.input :difficulty_level ,collection: 1..10, :input_html => {class: 'span4'} %>
<hr>

    <%= f.simple_fields_for :option do |a| %>
  <%= a.input :optionA , :input_html => { class: 'span18',:rows => 1} %>
  <%= a.input :optionB , :input_html => { class: 'span18',:rows => 1} %>
  <%= a.input :optionC , :input_html => { class: 'span18',:rows => 1} %>
  <%= a.input :optionD , :input_html => { class: 'span18',:rows => 1} %>
  <hr>
  <% end %>
<%= f.input :correct_choice, :input_html => { class: 'span18',:rows => 4} %>
  </div>
  <hr>
  <%= f.button :submit , :class=> "btn btn-primary" %>
<% end %>


</div>

</div>
</div>
</div>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<%= link_to 'New Question', new_question_path %>
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:correct_choice) %></th>
      <th><%= model_class.human_attribute_name(:difficulty_level) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>


      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @questions.each do |language| %>
      <tr>
        <td><%= link_to language.id, question_path(language) %></td>
        <td><%= language.name %></td>
        <td><%= language.correct_choice %></td>
        <td><%= language.difficulty_level  %></td>
        <td><%= language.created_at  %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_question_path(language), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      question_path(language),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_question_path,
            :class => 'btn btn-primary' %>

app/views/questions/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<br><br>

<div class="container-fluid">
  <div class="row-fluid">
   
    <div class="span9">
     
			<% @accept = Accept.new %>
			<% @que = @question_full %>
			<%= simple_form_for @accept, :url => "#" ,:method => 'post' do |f|%>

			<div class="panel panel-default">
			<div class="panel-heading"><b><%= @que.first.name %></b></div>
				<div class="panel-body">
						<% @queid = @que.first.id %>
						<%= f.input :questionid,:as => "hidden",:input_html => {:value => @queid } %>

						<%= f.collection_radio_buttons :option_retrieved, [[@que.first.option.optionA, @que.first.option.optionA],[@que.first.option.optionA,@que.first.option.optionA],[@que.first.option.optionC,@que.first.option.optionC],[@que.first.option.optionD,@que.first.option.optionD]], :first, :last %>

				</div>
		</div>

		<%= link_to 'Back' , :back %>

			<% end %>
    </div>
    <div class="span3">
					    	<ul class="list-group">
						<li class="list-group-item">
						Marks
							<span class="badge"><%= session[:mark] %></span>

						</li>
						<li class="list-group-item">
							Question NO.
							<span class="badge"><%= session[:question_no] %></span>

						</li>

					</ul>

    </div>
  </div>
</div>