config/routes.rb
TestAppBeta::Application.routes.draw do
  
  root 'home#index'

  get "home/index"
  get "user/test_results"
  get "user/tests_given"
  get "author/question_by_author"
  get "teach/teach_tut"
  get "author/tutorials_by_author"
  get "author/exercise_by_author"
  resources :languages

  
  get "profile/viewtest"
  get "starttest/select_level"
  get "starttest/random_test"
  get "starttest/start"
  post "starttest/result"
  get "starttest/show_result"
  get "starttest/end_test"
  get "user/test_show_details"
  post "starttest/total_question"

  devise_for :users
  resources :options
 
  resources :questions
  resources :accept

  resources :addimages

  get "learn/index"
  get "learn/tutorial"
  get "learn/exercise"
  get "student/index"
  post "learn/myfunc"
  get "learn/output"
 resources :exercises

  resources :tutorials

  get '/tutorials/showbylanguage/:tutorial_id'=> "tutorials#showbylanguage"

 

 

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end

    if user.role == "Author"
        can :manage , :all
    else
        can :read ,:all
    end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/accept.rb
class Accept < ActiveRecord::Base
	belongs_to :test
end

app/models/addimage.rb
class Addimage < ActiveRecord::Base
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
	belongs_to :tutorial
	mount_uploader :video , VideoUploader
end

app/models/language.rb
class Language < ActiveRecord::Base
has_many :tutorials
end

app/models/option.rb
class Option < ActiveRecord::Base
	belongs_to :question
end

app/models/q_no.rb
class QNo < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
	
	has_one :option
	belongs_to :test
	accepts_nested_attributes_for :option
	has_many :settests
	has_many :tests, through: :settests
	belongs_to :language
end
  

app/models/settest.rb
class Settest < ActiveRecord::Base
	belongs_to :question
	belongs_to :test
	belongs_to :user

	accepts_nested_attributes_for :accept

end

app/models/test.rb
class Test < ActiveRecord::Base
	has_many :questions , through: :settests
	has_many :settests
	belongs_to :user
	has_many :accepts
end

app/models/tutorial.rb
class Tutorial < ActiveRecord::Base
  belongs_to :language
  has_many :exercises
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :tests
end

app/controllers/starttest_controller.rb
class StarttestController < ApplicationController
 before_action :authenticate_user!
  def select_level
    
  	#@accept = Accept.new
  	#est = Test.new
	#testid = test.id

	session[:mark] = 0
	#@level_2 = Question.order("RANDOM()").where(:difficulty_level => 2).limit(1)
  	#@level_3 = Question.order("RANDOM()").where(:difficulty_level => 3).limit(1)

    #@total = @level_1 + @level_2 + @level_3 
	session[:question_no] = 1
  session[:level] = 5
  session[:level_temp] = 5.5
	@test = Test.new
	@test.user_id = current_user.id
	if @test.save
	session[:testid] = @test.id
    end

    #session[:total] = params[:q_no][:no]
    
    	#redirect_to starttest_start_path
	   #redirect_to starttest_start_path()
  end

  def random_test
  end

  def end_test
  	
    @total_marks = session[:mark]
    @test_id1 = session[:testid]
    @test = Test.where(:id => @test_id1)
    @test.first.marks = @total_marks
    @test.first.save

  end

  def result
  	@answer = params[:accept][:option_retrieved]
  	question = params[:accept][:questionid]
  	@q = Question.where(:id => question)
  	@correct_option = @q.first.correct_choice
	 
	 if @correct_option.eql? @answer
	   session[:mark] += 1
     #@increament = @q.first.difficulty_level.to_i/10
     session[:level_temp] =  0.5 + session[:level_temp]

	   fields = accept_params.merge(:isright => true,:test_id => session[:testid])
    else
      #@decrement = @q.first.difficulty_level/10
      session[:level_temp] = session[:level_temp]-0.5
	    fields = accept_params.merge(:isright => false,:test_id => session[:testid])
	 end
	   @accept = Accept.new(fields)
	   @accept.save
     session[:question_no] = session[:question_no] + 1
   
    if session[:question_no] == session[:total]
      redirect_to starttest_show_result_path
    end

     redirect_to starttest_start_path


  end

  def total_question

    session[:total] = params[:q_no][:no]
    redirect_to starttest_start_path(:total_questions => session[:total])

    
  end

  def check 
  end

  def start 


      x = session[:question_no].to_i
      y = session[:total].to_i
      if x == y+1
        redirect_to starttest_end_test_path
       
      end
#as
      #session[:total] = @total
      #if session[:question_no] == session[:total]
      #  redirect_to starttest_show_result_path
      #end
      if session[:level] < session[:level_temp] 
        if session[:level_temp] == session[:level] + 1
        session[:level] = session[:level_temp]
        end
        @level_user = session[:level]
      
        elsif session[:level] > session[:level_temp]
          if session[:level] == session[:level_temp] + 1
          session[:level] = session[:level_temp]
          end 
          @level_user = session[:level]
            elsif session[:level] == session[:level_temp]
            @level_user = session[:level]
            end
           
        

      
      @level_5 = Question.order("RANDOM()").where(:difficulty_level => @level_user).limit(1)
      @question_full = Question.where(:id => @level_5)
 
end

def show_result
	@tests = Test.where(:user_id => current_user.id)
end

private
    def accept_params
      params.require(:accept).permit(:questionid,:option_retrieved,:isright,:test_id)
    end
end

app/helpers/addimages_helper.rb
module AddimagesHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/learn_helper.rb
module LearnHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/starttest_helper.rb
module StarttestHelper
end

app/helpers/teach_helper.rb
module TeachHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/starttest/_question.html.erb
<br><br>

<div class="container-fluid">
  <div class="row-fluid">
   
    <div class="span9">
     
		<% @que = @question_full.first %>
			<% @accept = Accept.new %>
		
			<%= simple_form_for @accept, :url => starttest_result_path, :method => 'post' do |f|%>

			<div class="panel panel-default">
			<div class="panel-heading"><b><%= @que.name %></b></div>
				<div class="panel-body">
						<% @queid = @que.id %>
						<%= f.input :questionid,:as => "hidden",:input_html => {:value => @queid } %>

						<%= f.collection_radio_buttons :option_retrieved, [[@que.option.optionA, @que.option.optionA],[@que.option.optionA,@que.option.optionA],[@que.option.optionC,@que.option.optionC],[@que.option.optionD,@que.option.optionD]], :first, :last %>

				</div>
		</div>



		 	<%= f.button :submit ,"Next"%></li>


			<% end %>
    </div>
    <div class="span3">
					    	<ul class="list-group">
						<li class="list-group-item">
						Marks
							<span class="badge"><%= session[:mark] %></span>

						</li>
						<li class="list-group-item">
							Question NO.
							<span class="badge"><%= session[:question_no] %></span>

						</li>

					</ul>

    </div>
  </div>
</div>

app/views/starttest/end_test.html.erb
<div class="container">
	<div class="row">
		<div class="span6">
			<h3>You scored <b><%= @total_marks %></b> marks in test</h3>
			<% if @total_marks > 10 %>
				
			<%end%>
		</div>
		<div class="span6">

			<%=link_to "show Answers",user_test_show_details_path(:test_id => session[:testid]),:class => 'btn btn-primary'%>			
			
		</div>
	</div>
</div>

app/views/starttest/random_test.html.erb
<h1>Starttest#random_test</h1>
<p>Find me in app/views/starttest/random_test.html.erb</p>

app/views/starttest/select_level.html.erb
<div class="container">
			
			<h5>Select number of questions in test </h5>
			<% @qno = QNo.new %>
			<%= simple_form_for @qno, :url => starttest_total_question_path, :method => 'post' do |f|%>
			<%= f.input :no ,collection: [15,20,25,30], :input_html => {class: 'span4'}, label:false , :include_blank => false %>
			<%= f.submit :value => "Submit",:class => "btn btn-default" %>
			<% end %>	

</div>

app/views/starttest/show_result.html.erb
<br><br><br>

<table>
  <thead>
    <tr>
      <th>Tests Given by <%= current_user.first_name %></th>
      
    </tr>
  </thead>

  <tbody>
    <% @tests.each do |language| %>
      <tr>
        <td><%= language.id %></td>
        
    
      </tr>
    <% end %>
  </tbody>
</table>

app/views/starttest/start.html.erb
<div id ="container">
<div class ="row-fluid">
<div class="span2"></div>
<div class ="span10">
<%= render :partial => 'question' , :locals => { :que => @question_full } %>
</div>
</div>
</div>