config/routes.rb
TestAppBeta::Application.routes.draw do
  
  root 'home#index'

  get "home/index"
  get "user/test_results"
  get "user/tests_given"
  get "author/question_by_author"
  get "teach/teach_tut"
  get "author/tutorials_by_author"
  get "author/exercise_by_author"
  resources :languages

  
  get "profile/viewtest"
  get "starttest/select_level"
  get "starttest/random_test"
  get "starttest/start"
  post "starttest/result"
  get "starttest/show_result"
  get "starttest/end_test"
  get "user/test_show_details"
  post "starttest/total_question"

  devise_for :users
  resources :options
 
  resources :questions
  resources :accept

  resources :addimages

  get "learn/index"
  get "learn/tutorial"
  get "learn/exercise"
  get "student/index"
  post "learn/myfunc"
  get "learn/output"
 resources :exercises

  resources :tutorials

  get '/tutorials/showbylanguage/:tutorial_id'=> "tutorials#showbylanguage"

 

 

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end

    if user.role == "Author"
        can :manage , :all
    else
        can :read ,:all
    end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/accept.rb
class Accept < ActiveRecord::Base
	belongs_to :test
end

app/models/addimage.rb
class Addimage < ActiveRecord::Base
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
	belongs_to :tutorial
	mount_uploader :video , VideoUploader
end

app/models/language.rb
class Language < ActiveRecord::Base
has_many :tutorials
end

app/models/option.rb
class Option < ActiveRecord::Base
	belongs_to :question
end

app/models/q_no.rb
class QNo < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
	
	has_one :option
	belongs_to :test
	accepts_nested_attributes_for :option
	has_many :settests
	has_many :tests, through: :settests
	belongs_to :language
end
  

app/models/settest.rb
class Settest < ActiveRecord::Base
	belongs_to :question
	belongs_to :test
	belongs_to :user

	accepts_nested_attributes_for :accept

end

app/models/test.rb
class Test < ActiveRecord::Base
	has_many :questions , through: :settests
	has_many :settests
	belongs_to :user
	has_many :accepts
end

app/models/tutorial.rb
class Tutorial < ActiveRecord::Base
  belongs_to :language
  has_many :exercises
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :tests
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  before_action :set_option, only: [:show, :edit, :update, :destroy]

  # GET /options
  # GET /options.json
  def index
    @options = Option.all
  end

  # GET /options/1
  # GET /options/1.json
  def show
  end

  # GET /options/new
  def new
    @option = Option.new
  end

  # GET /options/1/edit
  def edit
  end

  # POST /options
  # POST /options.json
  def create
    @option = Option.new(option_params)

    respond_to do |format|
      if @option.save
        format.html { redirect_to @option, notice: 'Option was successfully created.' }
        format.json { render action: 'show', status: :created, location: @option }
      else
        format.html { render action: 'new' }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /options/1
  # PATCH/PUT /options/1.json
  def update
    respond_to do |format|
      if @option.update(option_params)
        format.html { redirect_to @option, notice: 'Option was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /options/1
  # DELETE /options/1.json
  def destroy
    @option.destroy
    respond_to do |format|
      format.html { redirect_to options_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_option
      @option = Option.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def option_params
      params.require(:option).permit(:optionA, :optionB, :optionC, :optionD)
    end
end

app/helpers/addimages_helper.rb
module AddimagesHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/learn_helper.rb
module LearnHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/teach_helper.rb
module TeachHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/options/_form.html.erb
<%= form_for(@option) do |f| %>
  <% if @option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@option.errors.count, "error") %> prohibited this option from being saved:</h2>

      <ul>
      <% @option.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :optionA %><br>
    <%= f.text_area :optionA %>
  </div>
  <div class="field">
    <%= f.label :optionB %><br>
    <%= f.text_area :optionB %>
  </div>
  <div class="field">
    <%= f.label :optionC %><br>
    <%= f.text_area :optionC %>
  </div>
  <div class="field">
    <%= f.label :optionD %><br>
    <%= f.text_area :optionD %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/options/edit.html.erb
<h1>Editing option</h1>

<%= render 'form' %>

<%= link_to 'Show', @option %> |
<%= link_to 'Back', options_path %>

app/views/options/index.html.erb
<h1>Listing options</h1>

<table>
  <thead>
    <tr>
      <th>Optiona</th>
      <th>Optionb</th>
      <th>Optionc</th>
      <th>Optiond</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @options.each do |option| %>
      <tr>
        <td><%= option.optionA %></td>
        <td><%= option.optionB %></td>
        <td><%= option.optionC %></td>
        <td><%= option.optionD %></td>
        <td><%= link_to 'Show', option %></td>
        <td><%= link_to 'Edit', edit_option_path(option) %></td>
        <td><%= link_to 'Destroy', option, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Option', new_option_path %>

app/views/options/new.html.erb
<h1>New option</h1>

<%= render 'form' %>

<%= link_to 'Back', options_path %>

app/views/options/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Optiona:</strong>
  <%= @option.optionA %>
</p>

<p>
  <strong>Optionb:</strong>
  <%= @option.optionB %>
</p>

<p>
  <strong>Optionc:</strong>
  <%= @option.optionC %>
</p>

<p>
  <strong>Optiond:</strong>
  <%= @option.optionD %>
</p>

<%= link_to 'Edit', edit_option_path(@option) %> |
<%= link_to 'Back', options_path %>