config/routes.rb
TestAppBeta::Application.routes.draw do
  
  root 'home#index'

  get "home/index"
  get "user/test_results"
  get "user/tests_given"
  get "author/question_by_author"
  get "teach/teach_tut"
  get "author/tutorials_by_author"
  get "author/exercise_by_author"
  resources :languages

  
  get "profile/viewtest"
  get "starttest/select_level"
  get "starttest/random_test"
  get "starttest/start"
  post "starttest/result"
  get "starttest/show_result"
  get "starttest/end_test"
  get "user/test_show_details"
  post "starttest/total_question"

  devise_for :users
  resources :options
 
  resources :questions
  resources :accept

  resources :addimages

  get "learn/index"
  get "learn/tutorial"
  get "learn/exercise"
  get "student/index"
  post "learn/myfunc"
  get "learn/output"
 resources :exercises

  resources :tutorials

  get '/tutorials/showbylanguage/:tutorial_id'=> "tutorials#showbylanguage"

 

 

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end

    if user.role == "Author"
        can :manage , :all
    else
        can :read ,:all
    end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/accept.rb
class Accept < ActiveRecord::Base
	belongs_to :test
end

app/models/addimage.rb
class Addimage < ActiveRecord::Base
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
	belongs_to :tutorial
	mount_uploader :video , VideoUploader
end

app/models/language.rb
class Language < ActiveRecord::Base
has_many :tutorials
end

app/models/option.rb
class Option < ActiveRecord::Base
	belongs_to :question
end

app/models/q_no.rb
class QNo < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
	
	has_one :option
	belongs_to :test
	accepts_nested_attributes_for :option
	has_many :settests
	has_many :tests, through: :settests
	belongs_to :language
end
  

app/models/settest.rb
class Settest < ActiveRecord::Base
	belongs_to :question
	belongs_to :test
	belongs_to :user

	accepts_nested_attributes_for :accept

end

app/models/test.rb
class Test < ActiveRecord::Base
	has_many :questions , through: :settests
	has_many :settests
	belongs_to :user
	has_many :accepts
end

app/models/tutorial.rb
class Tutorial < ActiveRecord::Base
  belongs_to :language
  has_many :exercises
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :tests
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  	
  end
end

app/helpers/addimages_helper.rb
module AddimagesHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/learn_helper.rb
module LearnHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/teach_helper.rb
module TeachHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.erb
<% if current_user.role == "Student" %>
<div class="main">
	<section class="page1">
		<br><br><br>
			<div class="container"> 
				<h2>
					<blockquote class="blockquote-reverse">Get what you want
						<small>Learn basics</small>
						</blockquote>
				</h2>
				<hr/>
				<%= link_to "Start Tutorials",learn_index_path, {:class => "btn btn-medium btn-info pull-right"} %>				
			</div>
			<br><br><br>
	</section>


	<section class="page5">
		<br><br><br>
		<div class="container">

		<h2><blockquote class="blockquote-reverse">
			Test your Knowledge

			<small>Give the test</small>
		</blockquote></h2>
					<hr/>
				<%= link_to "Start Test",starttest_select_level_path, {:class => "btn btn-medium btn-info pull-right"} %>	
			

		</div>
			
			
		<br><br><br>
		</section>

</div>







<% elsif current_user.role = "Author" %>

<div class="main">

	<section class="page1">
		<div class="container">
		<br><br><br>
		<h2><blockquote class="blockquote-reverse">
			Teach the world
			<small>Add your tutorials</small>
		</blockquote></h2>
		<hr/>
			<%= link_to "Add a Tutorial",new_tutorial_path, {:class => "btn btn-large btn-info pull-right"} %>
		</div>	
	</section>
	<section class="page2">
		<div class="container">
		<br><br><br>
			<h2><blockquote class="blockquote-reverse">
				Add your challange
				<small>Add your questions</small>
			</blockquote></h2>
			<hr/>	
			<%= link_to "Add a Question",new_question_path, {:class => "btn btn-large btn-info pull-right"} %>
			<br>
		</div>
		
	</section>
</div>

</div>	




<% end %>
<br><br><br><br>